# Generated by Django 6.1.1 on 2026-09-14 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категориянын аты')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категориялар',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Товардын аты')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баасы (сом)')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Сүрөтү')),
                ('description', models.TextField(blank=True, verbose_name='Сүрөттөмөсү')),
                ('available', models.BooleanField(default=True, verbose_name='Сатыкта бар')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товарлар',
            },
        ),
    ]
