# Generated by Django 6.1.1 on 2026-09-14 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Кардардын аты')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон номери')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Заказ түшкөн убакыт')),
                ('status', models.BooleanField(default=False, verbose_name='Аткарылды ушул заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Кайсы товар')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказдар',
            },
        ),
    ]
