# Generated by Django 6.1.1 on 2026-09-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_address',
            field=models.TextField(default='', verbose_name='Жеткирүү дареги (Адрес)'),
        ),
    ]
