# Generated by Django 6.1.1 on 2026-09-15 08:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_customer_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Жарыя (Товар)', 'verbose_name_plural': 'Жарыялар (Товарлар)'},
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Кошулган убактысы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='dynamic_properties',
            field=models.JSONField(blank=True, default=dict, verbose_name='Категориялык мүнөздөмөлөр'),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(default='Бишкек', max_length=150, verbose_name='Дареги (Жайгашкан жери)'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_name',
            field=models.CharField(default='Колдонуучу', max_length=100, verbose_name='Сатуучунун аты'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_phone',
            field=models.CharField(default='', max_length=20, verbose_name='Сатуучунун телефону'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Активдүү жарыя'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Толук мүнөздөмөсү'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='Товардын сүрөтү'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Жарыянын аты'),
        ),
    ]
